include:
  - board: cornix_left
    #shield: cornix_indicator
    artifact-name: cornix_left_default

  - board: cornix_ph_left
    #shield: cornix_indicator
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    #shield: cornix_indicator
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset

  - board: seeeduino_xiao_ble
    shield: cornix_yads dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: yads_dongle

  - board: seeeduino_xiao_ble
    shield: cornix_prospector prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: prospector_dongle

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset