include:
  - board: seeeduino_xiao_ble
    shield: cornix_dongle_adapter dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_dongle

  - board: cornix_left
    #shield: cornix_indicator
    artifact-name: cornix_left_default

  - board: cornix_ph_left
    #shield: cornix_indicator
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    #shield: cornix_indicator
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset